# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'puma', '~> 4.3'
gem 'rails', '~> 6.0.3'
gem 'redis', '~> 4.1', '>= 4.1.3'
gem 'sqlite3', '~> 1.4'

gem 'bootsnap', '>= 1.4.2', require: false

gem 'rack-cors'

gem 'feature_channel', path: '../feature_channel'
gem 'google-cloud-pubsub', '~> 2.4'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
